title: hecko

theme:

include:
  - _assets

kramdown:
  input: GFM
  hard_wrap: true
  gfm_quirks: [paragraph_end, no_auto_typographic]
  header_offset: 1
  smart_quotes: ["apos", "apos", "quot", "quot"]

plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter

optional_front_matter:
  remove_originals: true
